### ISSUE TITLE
API: Hacer que los campos 'first_name' y 'last_name' del modelo Usuarios sean obligatorios

### ISSUE THREAD

**Issue by MauricioMiramontes** [MauricioMiramontes/PrototipoSIRMAT#12]
En nuestro sistema sera requerido que el usuario de su nombre/s y su apellido paterno para poder realizar su registro, ahora mismo en la API estos dos campos son opcionales.

Se deberá hacer modificaciones en el archivo `models.py` dentro de `Usuarios`  y agregar los campos `first_name` y `last_name` de tipo `models.CharField()`.
De tal forma que, si se intenta hacer un registro de un nuevo usuario y no se proporcionan estos campos la API responderá de esta manera:
```json
{
    "first_name": [
        "This field is required."
    ],
    "last_name": [
        "This field is required."
    ]
}
```
Para en la [documentacion](https://docs.djangoproject.com/en/3.2/topics/db/models/#field-options) oficial de Django se explica que se debe hacer para que un campo sea obligatorio

Una vez terminado esto, dentro de la función `def create(self, validated_data):` que se encuentra en el archivo `serializers.py` dentro de `Usuarios` habrá código que es innecesario y deberá ser cambiado de la siguiente manera:

- La funcion debera ser cambiada de esto:
```python
def create(self, validated_data):
        try:
            user = User( # Los 5 campos obligatorios que deben estar en una peticion de POST 
                email = validated_data['email'],
                username = validated_data['username'],
                telefono = validated_data['telefono'],
                first_name = validated_data['first_name'],
                last_name = validated_data['last_name']
            )
        except: # En caso de que alguno falte debemos enviar un error 
            raise serializers.ValidationError({
                'Error': 'Missing fields',
                'field required': ['email','username', 'telefono', 'first_name', 'last_name']
            })
        user.set_password(validated_data['password'])
        user.save()
        return user

```
- A esto: 
```python
def create(self, validated_data):
        # Se guarda el nuevo usuario con los 5 campos obligatorios
        user = User(  
            email = validated_data['email'],
            username = validated_data['username'],
            telefono = validated_data['telefono'],
            first_name = validated_data['first_name'],
            last_name = validated_data['last_name']
        )
        user.set_password(validated_data['password'])
        user.save()
        return user
```

Esta función se utiliza para asegurar que la contraseña sea cifrada antes de ser guardada en la base de datos, como con los cambios anteriores se va a validar desde antes se haya recibido nombre (`first_name`) y apellido (`last_name`) para el registro de usuario entonces ya no son necesarios el `try` y el `except`

**Comment by eduardordl97** [comment]
.
