### ISSUE TITLE
API: Cambiar la logica de todas las peticiones DELETE

### ISSUE THREAD

**Issue by MauricioMiramontes** [MauricioMiramontes/PrototipoSIRMAT#13]
Normalmente en un sistema cuando se quiere eliminar algo de la base de datos en lugar de borrarlo se "Da de baja", es decir ya no se toma en cuenta ese registro pero sigue existiendo en la base de datos.
El objetivo de esto es que, si en el futuro se requiere hacer algún reporte o análisis de la base de datos se seguirá teniendo la información de esos registros por si llegan a ser necesarios a pesar de que ya no están activos.

Para poder realizar esto sera necesario hacer lo siguiente: 

1. En el archivo `models.py` de cada App del sistema se debera agregar un nuevo campo con el nombre `is_active` este campo sera de tipo `models.BooleanField` que por defecto sera `True`
NOTA 1: Como se están haciendo cambios a los modelos se debe hacer `makemigrations` y `migrate` antes de correr la API
NOTA 2: No es necesario hacer este paso para el modelo de `Usuarios` ya que usuarios por defecto ya cuenta con este campo

2. En el archivo `views.py` de cada App del sistema de deberá cambiar la lógica de la peticion DELETE que se encuentra en la función `def delete(self, request):` para que, en lugar de eliminar ese registro, se cambie el valor de `is_active` de `True` a `False`

**Comment by eduardordl97** [comment]
.

**Comment by MauricioMiramontes** [comment]
Falta cambiar la lógica de `DELETE` para `Usuarios`
