### ISSUE TITLE
API: Crear interaccion con LabelStudio para DetallesMuestra

### ISSUE THREAD

**Issue by MauricioMiramontes** [MauricioMiramontes/PrototipoSIRMAT#15]
La ultima interacción pendiente de nuestra API con label studio es que cuando se registren los detalles de una muestra también se debe dar la descripción a el proyecto de label studio que este relacionado con la muestra.

Ahora mismo cuando se registra una nueva muestra en la API de SIRMAT tambien se va a crear un nuevo projecto en la base de datos de label studio, se sabra que estos dos estan relacionados por que el campo `idMuestra` sera el mismo que el campo `id` del projecto de label studio

La tabla que contiene todos los datos de los projectos de label studio tiene por nombre `project` y, dentro de esta tabla se encuentra un campo con nombre `description`

Se deberá hacer lo siguiente:

1. Crear el archivo `Label_Studio_db.py` dentro de `DetallesMuestra`
2. Dentro de este archivo se debera definir dos funciones: 
    - `def agregar_detallesmuestra_ls(id_muestra, descripcion):`
    - `def editar_detallesmuestra_ls(id_muestra, descripcion):`
3. Estas funciones deberán tomar lo que hayan recibido en la variable `descripcion`  y agregarlo a el campo `description` del registro cuyo `id` coincida con el valor de la variable `id_muestra` 

Como referencia se puede utilizar el [archivo](https://github.com/MauricioMiramontes/PrototipoSIRMAT/blob/main/SIRMAT/Muestra/Label_Studio_db.py) `Label_Studio_db.py` que se encuentra dentro de `Muestra` y la [documentacion](https://docs.python.org/3/library/sqlite3.html) de la libreria sqlite3 de python

**Comment by eduardordl97** [comment]
.
