### ISSUE TITLE
Error: formato de Fotografias

### ISSUE THREAD

**Issue by LuisManuelRosalesGutierrez** [MauricioMiramontes/PrototipoSIRMAT#24]
Al subir fotografías se deberían de ver en la parte de Label Studio, sin embargo, al subir una fotografia en formato que no sea .png (como por ejemplo .jpg) el sistema de no reconoce y en Label Studio muestra un error al cargar la imagen, esto no seria problema de no ser por que al hacer un POST (en postman) con una fotografía de este formato (.jpg) si deja crearlo, pero como lo dije al principio en Label Studio no se muestra la imagen correctamente.

**Comment by MauricioMiramontes** [comment]
Parece ser que el problema no es el formato de la imagen, el problema esta en el nombre con el que guardamos la fotografía:

Django automáticamente cambia los espacios en blanco por renglones bajos, por ejemplo:

`Nueva Foto.jpg` lo cambia a `Nueva_Foto.jpg` antes de guardarlo, sin embarlo label studio sigue buscando la foto con nombre `Nueva Foto.jpg`

Porfavor que alguien mas confirme esto.

1. Subir una foto a la API con formato `.jpg` cuyo nombre NO contenga espacios en blanco y revisar si aparece en label studio de forma correcta.
2. Subir una foto a la API con formato `.jpg` cuyo nombre SI contenga espacios en blanco y revisar si aparece en label studio
