### ISSUE TITLE
API: Agregar autenticación para todas las apps de la API

### ISSUE THREAD

**Issue by MauricioMiramontes** [MauricioMiramontes/PrototipoSIRMAT#8]
Esta tarea sera mas que nada copiar y pegar y hacer pruebas de que todo funcione. Lo mas tardado serán las pruebas.

Para que se requiera el Token como autenticación en una parte de la API es necesario agregar al archivo `views.py` de todas las Apps las siguientes lineas: 
- **Como referencia se puede utilizar el archivo** `views.py` **que se encuentra dentro de** `Trampas`.

- En las importaciones agregar:

```python
# Importar clase Authentication
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
```
- Dentro de la `APIView` agregar:
```python
authentication_classes = [TokenAuthentication]
permission_classes = [IsAuthenticated]
```
Con esto ya sera requerido el Token para realizar todas las operaciones (`GET`, `POST`, `PUT`, `DELETE`) de esa app, por lo tanto se deberá de probar que cada una de ellas siga funcionando solo si se proporciona el Token dentro de la peticion y si no se proporciona o se proporciona un Token invalido que la API responda con el error adecuado.

Como mandar un Token en Postman para autenticacion:
-------------------------------------------------------------------------------

Dentro de la opcion `Headers` que esta del lado izquierdo de `Body` hay que proporcionar un parametro con nombre `Authorization` y con un valor `Token Caracteres_del_Token` es importante que haya un espacio en blanco entre la palabra `Token` y `Caracteres_del_Token`. 

Adjunto una imagen de ejemplo de una operacion `GET` que proporciona un Token para autenticarse.

![imagen](https://user-images.githubusercontent.com/61033998/121090749-a1ef8d00-c7ae-11eb-8703-99e3924436f3.png)

**Comment by LuisManuelRosalesGutierrez** [comment]
.
