### ISSUE TITLE
API: Modificar funcion __str__ de cada modelo

### ISSUE THREAD

**Issue by MauricioMiramontes** [MauricioMiramontes/PrototipoSIRMAT#9]
Esta tarea sera solo modificar una linea en cada archivo `models.py` de cada una de las Apps.

Dentro de ese archivo se encuentra una función llamada:
```python
def __str__(self):
    return(#Regresa algo)
```

Necesitamos que esta funcion siempre regrese en formato `str` el valor del campo que se este usando como id para ese modelo. 
Por ejemplo: Para la app `Trampas` la funcion `__str__(self):` debe regresar unicamente el valor del campo `idcTrampas` en formato `str`.

Realizar este cambio para todas las Apps dentro de la API.

**Comment by Ulises-Portuguez** [comment]
.
